server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/museum_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    
logging:
  level:
    root: INFO
    com.example.museum: DEBUG  # 设置应用包的日志级别为DEBUG
    org.hibernate.SQL: DEBUG
    
# 特征提取服务配置
feature:
  extraction:
    service:
      url: http://localhost:5000
      
# 临时文件路径
museum:
  temp:
    path: temp
